In [1]:
import h5py
import numpy as np

# Define the file path
file_path = "50.h5"

# Open the HDF5 file
with h5py.File(file_path, 'r') as hdf:
    # Access the dataset at the path /frames
    frames = hdf['/frames']

    # Read the data into a NumPy array
    data = np.array(frames)

    # Print the shape of the data
    print("Shape of the data:", data.shape)

    # Process the data as needed
    # For example, you can calculate the average frame
    avg_frame = np.mean(data, axis=0)

    # Print the average frame
    print("Average frame:", avg_frame)

Shape of the data: (50, 354, 512)
Average frame: [[15.04 17.58 13.9  ... 23.86 23.96 23.96]
 [15.04 17.58 13.9  ... 22.66 22.52 22.52]
 [15.04 17.58 13.9  ... 21.86 21.86 21.86]
 ...
 [25.34 28.42 24.58 ...  7.06  6.62  6.62]
 [25.34 28.84 24.24 ...  7.16  7.16  6.62]
 [24.9  28.   23.74 ...  7.16  7.16  6.62]]


In [3]:
frames

<Closed HDF5 dataset>

In [4]:
import h5py
from datetime import datetime

file= "/home/brueckner/nomad-distro-dev/packages/unicornone-rheed/tests/data/50.h5"

with h5py.File(file, 'r') as hdf:
                attributes = {
                    'avg_frame_rate': hdf.attrs.get('avg_frame_rate', None),
                    'chunk_size': hdf.attrs.get('chunk_size', None),
                    'data_id': hdf.attrs.get('data_id', None),
                    'data_stream': hdf.attrs.get('data_stream', None),
                    'dims': hdf.attrs.get('dims', None),
                    'end_unix_ms_utc': hdf.attrs.get('end_unix_ms_utc', None),
                    'is_rotating': hdf.attrs.get('is_rotating', None),
                    'is_stream': hdf.attrs.get('is_stream', None),
                    'raw_frame_rate': hdf.attrs.get('raw_frame_rate', None),
                    'start_unix_ms_utc': hdf.attrs.get('start_unix_ms_utc', None)
                }

In [5]:
hdf.attrs.get('start_unix_ms_utc', None)

ValueError: Invalid location identifier (invalid location identifier)

In [6]:
attributes

{'avg_frame_rate': b'10',
 'chunk_size': b'50',
 'data_id': b'362cfd0f-fa1b-48f7-b838-19e91e3be5d8',
 'data_stream': b'rheed',
 'dims': b'50,354,512',
 'end_unix_ms_utc': b'1741617010313',
 'is_rotating': b'0',
 'is_stream': b'1',
 'raw_frame_rate': b'10',
 'start_unix_ms_utc': b'1741616987823'}